name: Deploy Node.js Application to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          mkdir -p /var/www/chatbot_server/
          cd /var/www/chatbot_server/
          git pull origin main || git clone git@github.com:Bubo101/AI-medical-chatbot.git .
          npm install
          pm2 restart chatbot_server || pm2 start npm --name "chatbot_server" -- run start:pm2

