name: Deploy React Application to GitHub Pages

on:
  push:
    branches:
      - main  # Or any other branch you want to deploy from

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.12.1' # Or the version you use, ensure it matches your development environment

      - name: Install dependencies
        run: npm install
        working-directory: ./chatbot_ui

      - name: Build
        run: npm run build
        working-directory: ./chatbot_ui

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages  # This is the branch the built site will be pushed to
          folder: chatbot_ui/build  # The folder the action should deploy, this should be the build output directory
