name: Deploy React App to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.1.1

      - name: Install Dependencies
        run: cd chatbot_ui && npm install

      - name: Build React App
        run: cd chatbot_ui && npm run build

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: chatbot_ui/build # The folder the action should deploy.


#actions/checkout@v4.1.1
#actions/setup-node@v4.0.2
#JamesIves/github-pages-deploy-action@4.1.4