name: Deploy Node.js Application to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          # Ensure the working directory exists
          mkdir -p /var/www/chatbot_server/
          cd /var/www/
          # Pull if the repo already exists, clone if it does not
          if [ -d "chatbot_server/.git" ]; then
            cd chatbot_server && git pull origin main && cd ..
          else
            git clone git@github.com:Bubo101/AI-medical-chatbot.git chatbot_server/
            cd chatbot_server
          fi
          # Navigate to the chatbot_server directory and perform npm install
          cd chatbot_server
          npm install
          # Restart the app with PM2, or start it if it's not running
          pm2 restart chatbot_server || pm2 start npm --name "chatbot_server" -- run start
